services:
  toolbox-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toolbox-site
    restart: unless-stopped
    # volumes:
    #   - ./config/llm.json:/usr/share/nginx/html/config/llm.json:ro
    ports:
      - "127.0.0.1:8080:80"
